<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use App\Products;

class productsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Products::create([
            'product_photo' => 'FB_IMG_1519731923768_1565103481.jpg',
            'product_name' => 'Dress2',
            'product_code' => 'Dress-002',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '43',
            'product_stocks' => '49',
            'product_desc' => 'Dress sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1519731957767.jpg',
            'product_name' => 'Dress3',
            'product_code' => 'Dress-003',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => 'Large',
            'product_category' => '43',
            'product_stocks' => '49',
            'product_desc' => 'Dress sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1529064181989.jpg',
            'product_name' => 'Dress4',
            'product_code' => 'Dress-004',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '43',
            'product_stocks' => '49',
            'product_desc' => 'Dress sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1529064195210.jpg',
            'product_name' => 'Dress5',
            'product_code' => 'Dress-005',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '43',
            'product_stocks' => '49',
            'product_desc' => 'Dress sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1529064201859.jpg',
            'product_name' => 'Dress6',
            'product_code' => 'Dress-006',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '43',
            'product_stocks' => '49',
            'product_desc' => 'Dress sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1529215847750.jpg',
            'product_name' => 'Dress7',
            'product_code' => 'Dress-007',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '43',
            'product_stocks' => '49',
            'product_desc' => 'Dress sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1529242918618.jpg',
            'product_name' => 'Dress8',
            'product_code' => 'Dress-008',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '43',
            'product_stocks' => '49',
            'product_desc' => 'Dress sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1529502964430.jpg',
            'product_name' => 'Short1',
            'product_code' => 'Short-001',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '46',
            'product_stocks' => '49',
            'product_desc' => 'Short sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1529502966992.jpg',
            'product_name' => 'Short2',
            'product_code' => 'Short-002',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '46',
            'product_stocks' => '49',
            'product_desc' => 'Short sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1529502972301.jpg',
            'product_name' => 'Short3',
            'product_code' => 'Short-003',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '46',
            'product_stocks' => '49',
            'product_desc' => 'Short sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1529502979932.jpg',
            'product_name' => 'Short4',
            'product_code' => 'Short-004',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '46',
            'product_stocks' => '49',
            'product_desc' => 'Short sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1529502982455.jpg',
            'product_name' => 'Short5',
            'product_code' => 'Short-005',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '46',
            'product_stocks' => '49',
            'product_desc' => 'Short sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1532072723284.jpg',
            'product_name' => 'Attire1',
            'product_code' => 'Attire-001',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1532184188588.jpg',
            'product_name' => 'Attire2',
            'product_code' => 'Attire-002',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1519731923768_1565103481.jpg',
            'product_name' => 'Attire3',
            'product_code' => 'Attire-003',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1532184550030.jpg',
            'product_name' => 'Attire4',
            'product_code' => 'Attire-004',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896479786.jpg',
            'product_name' => 'Shoes1',
            'product_code' => 'Shoes1-001',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '44',
            'product_stocks' => '49',
            'product_desc' => 'Shoes sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896557256.jpg',
            'product_name' => 'Attire5',
            'product_code' => 'Attire-005',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896560914.jpg',
            'product_name' => 'Attire6',
            'product_code' => 'Attire-006',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896567732.jpg',
            'product_name' => 'Attire7',
            'product_code' => 'Attire-007',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896575467.jpg',
            'product_name' => 'Attire8',
            'product_code' => 'Attire-008',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896579996.jpg',
            'product_name' => 'Attire9',
            'product_code' => 'Attire-009',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896586847.jpg',
            'product_name' => 'Attire10',
            'product_code' => 'Attire-010',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896597607.jpg',
            'product_name' => 'Attire11',
            'product_code' => 'Attire-011',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896601816.jpg',
            'product_name' => 'Attire12',
            'product_code' => 'Attire-012',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896612128.jpg',
            'product_name' => 'Attire13',
            'product_code' => 'Attire-013',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896615785.jpg',
            'product_name' => 'Attire14',
            'product_code' => 'Attire-014',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896619093.jpg',
            'product_name' => 'Attire15',
            'product_code' => 'Attire-015',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896631657.jpg',
            'product_name' => 'Attire16',
            'product_code' => 'Attire-016',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896635083.jpg',
            'product_name' => 'Attire17',
            'product_code' => 'Attire-017',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896638577.jpg',
            'product_name' => 'Attire18',
            'product_code' => 'Attire-018',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896641564.jpg',
            'product_name' => 'Attire19',
            'product_code' => 'Attire-019',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896645846.jpg',
            'product_name' => 'Attire20',
            'product_code' => 'Attire-020',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896654515.jpg',
            'product_name' => 'Attire21',
            'product_code' => 'Attire-021',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896658508.jpg',
            'product_name' => 'Attire22',
            'product_code' => 'Attire-022',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533896692092.jpg',
            'product_name' => 'Attire23',
            'product_code' => 'Attire-023',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897116434.jpg',
            'product_name' => 'Attire24',
            'product_code' => 'Attire-024',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897123672.jpg',
            'product_name' => 'Polo1',
            'product_code' => 'Polo-001',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '48',
            'product_stocks' => '49',
            'product_desc' => 'Polo sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897129822.jpg',
            'product_name' => 'Attire25',
            'product_code' => 'Attire-025',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897136583.jpg',
            'product_name' => 'Attire26',
            'product_code' => 'Attire-026',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897143617.jpg',
            'product_name' => 'Attire27',
            'product_code' => 'Attire-027',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897148028.jpg',
            'product_name' => 'Attire28',
            'product_code' => 'Attire-028',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897191372.jpg',
            'product_name' => 'Attire29',
            'product_code' => 'Attire-029',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897193575.jpg',
            'product_name' => 'Attire30',
            'product_code' => 'Attire-030',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897195881.jpg',
            'product_name' => 'Attire31',
            'product_code' => 'Attire-031',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897204893.jpg',
            'product_name' => 'Attire32',
            'product_code' => 'Attire-032',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897215378.jpg',
            'product_name' => 'Attire33',
            'product_code' => 'Attire-033',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897323636.jpg',
            'product_name' => 'Attire35',
            'product_code' => 'Attire-035',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897328293.jpg',
            'product_name' => 'Attire36',
            'product_code' => 'Attire-036',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897334011.jpg',
            'product_name' => 'Attire37',
            'product_code' => 'Attire-037',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897343615.jpg',
            'product_name' => 'Attire38',
            'product_code' => 'Attire-038',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897354313.jpg',
            'product_name' => 'Attire39',
            'product_code' => 'Attire-039',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897383835.jpg',
            'product_name' => 'Attire40',
            'product_code' => 'Attire-040',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897391409.jpg',
            'product_name' => 'Attire41',
            'product_code' => 'Attire-041',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897396264.jpg',
            'product_name' => 'Attire42',
            'product_code' => 'Attire-042',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897423271.jpg',
            'product_name' => 'Bag1',
            'product_code' => 'Bag-001',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '45',
            'product_stocks' => '49',
            'product_desc' => 'Bag sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897532440.jpg',
            'product_name' => 'Attire43',
            'product_code' => 'Attire-043',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897543414.jpg',
            'product_name' => 'Attire44',
            'product_code' => 'Attire-044',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897549161.jpg',
            'product_name' => 'Attire45',
            'product_code' => 'Attire-045',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533897582713.jpg',
            'product_name' => 'Attire46',
            'product_code' => 'Attire-046',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '47',
            'product_stocks' => '49',
            'product_desc' => 'Attire sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533898084768.jpg',
            'product_name' => 'Bag3',
            'product_code' => 'Bag-003',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '45',
            'product_stocks' => '49',
            'product_desc' => 'Bag sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'FB_IMG_1533898152204.jpg',
            'product_name' => 'Shoes2',
            'product_code' => 'Shoes-002',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '44',
            'product_stocks' => '49',
            'product_desc' => 'Shoes sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'L9076.jpg',
            'product_name' => 'Muscle shirt',
            'product_code' => 'L9076',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '43',
            'product_stocks' => '49',
            'product_desc' => 'L9076 sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'L9083.jpg',
            'product_name' => 'Moss Green Blouse',
            'product_code' => 'L9083',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '43',
            'product_stocks' => '49',
            'product_desc' => 'L9083 sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => '085.jpg',
            'product_name' => 'Ruffled shirt',
            'product_code' => '085',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '43',
            'product_stocks' => '49',
            'product_desc' => '085 sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'L9086.jpg',
            'product_name' => 'Lace blouse',
            'product_code' => 'L9086',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '43',
            'product_stocks' => '49',
            'product_desc' => 'L9086 sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'Dress19.1Collection-F254.jpg',
            'product_name' => 'Dress 19 1 Collection ',
            'product_code' => 'F254',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '43',
            'product_stocks' => '49',
            'product_desc' => 'F254 sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'Mouse.jpg',
            'product_name' => 'Mickey Mouse',
            'product_code' => 'B010',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '45',
            'product_stocks' => '49',
            'product_desc' => 'B010 sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
        Products::create([
            'product_photo' => 'VintageBag.jpg',
            'product_name' => 'Vintage Bag',
            'product_code' => 'VA20',
            'product_price' => '150',
            'product_price_previous' => '150',
            'product_size' => '1',
            'product_category' => '45',
            'product_stocks' => '49',
            'product_desc' => 'VA20 sample',
            'product_date' => Carbon::now()->format('Y-m-d H:i:s'),
        ]);
    }
}
